vim.g.colors_name = "modus"
vim.o.termguicolors = true

local function extends(what)
    return function (with)
        return function ()
            local result = vim.api.nvim_get_hl(0, { create = false, name = what })
            if getmetatable(result) == getmetatable(vim.empty_dict()) then
                return nil
            end
            return vim.tbl_deep_extend("force", result, with)
        end
    end
end

local function link(with)
    return {
        link = with
    }
end

local palette = {
    none                      = "NONE",
    bg_active                 = "#c9b9b0",
    bg_added                  = "#c3ebc1",
    bg_added_faint            = "#dcf8d1",
    bg_added_fringe           = "#6cc06c",
    bg_added_refine           = "#acd6a5",
    bg_blue_intense           = "#bfc9ff",
    bg_blue_nuanced           = "#ebebff",
    bg_blue_subtle            = "#ccdfff",
    bg_changed                = "#ffdfa9",
    bg_changed_faint          = "#ffefbf",
    bg_changed_fringe         = "#c0b200",
    bg_changed_refine         = "#fac090",
    bg_clay                   = "#f1c8b5",
    bg_completion             = "#f0c1cf",
    bg_cyan_intense           = "#a4d5f9",
    bg_cyan_nuanced           = "#e1f3fc",
    bg_cyan_subtle            = "#bfefff",
    bg_diff_context           = "#efe9df",
    bg_dim                    = "#efe9dd",
    bg_graph_blue_0           = "#7f90ff",
    bg_graph_blue_1           = "#a6c0ff",
    bg_graph_cyan_0           = "#70d3f0",
    bg_graph_cyan_1           = "#afefff",
    bg_graph_green_0          = "#45c050",
    bg_graph_green_1          = "#75ef30",
    bg_graph_magenta_0        = "#e07fff",
    bg_graph_magenta_1        = "#fad0ff",
    bg_graph_red_0            = "#ef7969",
    bg_graph_red_1            = "#ffaab4",
    bg_graph_yellow_0         = "#ffcf00",
    bg_graph_yellow_1         = "#f9ff00",
    bg_green_intense          = "#8adf80",
    bg_green_nuanced          = "#e0f5e0",
    bg_green_subtle           = "#b3fabf",
    bg_hl_line                = "#f1d5d0",
    bg_hover                  = "#b2e4dc",
    bg_hover_secondary        = "#dfe09f",
    bg_inactive               = "#dfd5cf",
    bg_lavender               = "#dfcdfa",
    bg_magenta_intense        = "#dfa0f0",
    bg_magenta_nuanced        = "#f6e7ff",
    bg_magenta_subtle         = "#ffddff",
    bg_main                   = "#fbf7f0",
    bg_mode_line_active       = "#cab9b2",
    bg_mode_line_inactive     = "#dfd9cf",
    bg_ochre                  = "#f0e3c0",
    bg_paren_expression       = "#efd3f5",
    bg_paren_match            = "#7fdfcf",
    bg_red_intense            = "#ff8f88",
    bg_red_nuanced            = "#ffe8f0",
    bg_red_subtle             = "#ffcfbf",
    bg_region                 = "#c2bcb5",
    bg_removed                = "#f4d0cf",
    bg_removed_faint          = "#ffe9e5",
    bg_removed_fringe         = "#d84a4f",
    bg_removed_refine         = "#f3b5a7",
    bg_sage                   = "#c0e7d4",
    bg_status_line_active     = "#cab9b2",
    bg_status_line_inactive   = "#dfd9cf",
    bg_tab_alternate          = "#c8b8ca",
    bg_tab_bar                = "#e0d4ce",
    bg_tab_current            = "#fbf7f0",
    bg_tab_other              = "#c8b8b2",
    bg_yellow_intense         = "#f3d000",
    bg_yellow_nuanced         = "#f9ead0",
    bg_yellow_subtle          = "#fff576",
    blue                      = "#0031a9",
    blue_cooler               = "#0000b0",
    blue_faint                = "#003497",
    blue_intense              = "#0000ff",
    blue_warmer               = "#3546c2",
    border                    = "#9f9690",
    border_highlight          = "#5c3f3d",
    border_mode_line_active   = "#545454",
    border_mode_line_inactive = "#a59a94",
    cyan                      = "#00598b",
    cyan_cooler               = "#005f5f",
    cyan_faint                = "#304463",
    cyan_intense              = "#008899",
    cyan_warmer               = "#32548f",
    fg_active                 = "#0a0a0a",
    fg_added                  = "#005000",
    fg_added_intense          = "#006700",
    fg_alt                    = "#193668",
    fg_changed                = "#553d00",
    fg_changed_intense        = "#655000",
    fg_clay                   = "#63192a",
    fg_dim                    = "#595959",
    fg_inactive               = "#404148",
    fg_lavender               = "#443379",
    fg_main                   = "#000000",
    fg_mode_line_active       = "#000000",
    fg_mode_line_inactive     = "#585858",
    fg_ochre                  = "#573a30",
    fg_region                 = "#000000",
    fg_removed                = "#8f1313",
    fg_removed_intense        = "#aa2222",
    fg_sage                   = "#124b41",
    gold                      = "#80601f",
    green                     = "#006300",
    green_cooler              = "#00603f",
    green_faint               = "#2a5045",
    green_intense             = "#008900",
    green_warmer              = "#306010",
    indigo                    = "#4a3a8a",
    magenta                   = "#721045",
    magenta_cooler            = "#531ab6",
    magenta_faint             = "#7c318f",
    magenta_intense           = "#dd22dd",
    magenta_warmer            = "#8f0075",
    maroon                    = "#731c52",
    modeline_err              = "#7f0000",
    modeline_info             = "#002580",
    modeline_warning          = "#5f0070",
    olive                     = "#56692d",
    pink                      = "#7b435c",
    red                       = "#a60000",
    red_cooler                = "#a0132f",
    red_faint                 = "#C2708B",
    red_intense               = "#d00000",
    red_warmer                = "#972500",
    rust                      = "#8a290f",
    slate                     = "#2f3f83",
    yellow                    = "#6d5000",
    yellow_cooler             = "#602938",
    yellow_faint              = "#574316",
    yellow_intense            = "#808000",
    yellow_warmer             = "#894000",

    error         = "red_cooler",
    warning       = "yellow_cooler",
    info          = "blue_cooler",
    hint          = "cyan_faint",
    ok            = "green_cooler",
    success       = "fg_added",
    visual        = "bg_magenta_intense",
}

-- link aliases
for key, value in pairs(palette) do
    if value ~= "NONE" and string.sub(value, 1, 1) ~= '#' and palette[key] then
        palette[key] = palette[value]
    end
end

vim.g.terminal_color_0  = palette.bg_main
vim.g.terminal_color_8  = palette.bg_dim
vim.g.terminal_color_7  = palette.fg_main
vim.g.terminal_color_15 = palette.fg_dim
vim.g.terminal_color_1  = palette.red
vim.g.terminal_color_9  = palette.red_intense
vim.g.terminal_color_2  = palette.green
vim.g.terminal_color_10 = palette.green_intense
vim.g.terminal_color_3  = palette.yellow
vim.g.terminal_color_11 = palette.yellow_intense
vim.g.terminal_color_4  = palette.blue
vim.g.terminal_color_12 = palette.blue_intense
vim.g.terminal_color_5  = palette.magenta
vim.g.terminal_color_13 = palette.magenta_intense
vim.g.terminal_color_6  = palette.cyan
vim.g.terminal_color_14 = palette.cyan_intense

local c = palette

local definitions = {

    Normal         = { fg = c.fg_main,                 bg = c.bg_main },
    NormalNC       = link "Normal",
    NormalSB       = { fg = c.fg_dim,                  bg = c.bg_dim },
    NormalFloat    = { fg = c.fg_active,               bg = c.bg_main },
    FloatBorder    = { fg = c.border_highlight,        bg = c.bg_main },
    FloatTitle     = { fg = c.border_highlight,        bg = c.bg_main },
    FloatFooter    = link "FloatTitle",
    Folded         = { fg = c.green_faint,             bg = c.bg_dim },
    LineNr         = { fg = c.fg_main,                 bg = c.bg_dim },
    LineNrAbove    = { fg = c.fg_dim,                  bg = c.bg_dim },
    LineNrBelow    = { fg = c.fg_dim,                  bg = c.bg_dim },
    CursorLineNr   = { fg = c.fg_active,               bg = c.bg_active,      bold = true },
    SignColumn     = { fg = c.fg_dim,                  bg = c.bg_dim },
    SignColumnSB   = extends "NormalSB" {},
    CursorLine     = { fg = c.none,                    bg = c.bg_hl_line },
    CursorColumn   = { fg = c.none,                    bg = c.bg_hl_line },
    NonText        = { fg = c.bg_dim },
    ErrorMsg       = { fg = c.fg_main,                 bg = c.bg_red_intense },
    Conceal        = { fg = c.yellow_faint },
    Cursor         = { fg = c.bg_main,                 bg = c.red_intense },
    lCursor        = link "Cursor",
    ColorColumn    = { fg = c.fg_main,                 bg = c.bg_dim },
    CursorLineFold = link "CursorLineNr",
    CursorLineSign = link "CursorLineNr",
    FoldColumn     = { fg = c.fg_inactive,             bg = c.bg_inactive },
    Search         = { fg = c.fg_main,                 bg = c.bg_blue_intense },
    IncSearch      = { fg = c.fg_main,                 bg = c.bg_yellow_intense },
    CurSearch      = link "IncSearch",
    Substitute     = { fg = c.fg_main,                 bg = c.bg_red_intense },
    Visual         = { fg = c.fg_main,                 bg = c.bg_magenta_intense },
    QuickFixLine   = link "Visual",
    Pmenu          = { fg = c.fg_active,               bg = c.bg_active },
    PmenuSel       = { fg = c.bg_active,               bg = c.fg_active },
    PmenuSbar      = { fg = c.fg_active,               bg = c.bg_dim },
    PmenuThumb     = link "Cursor",
    Menu           = link "Pmenu",
    Scrollbar      = link "PmenuSbar",
    Directory      = { fg = c.blue },
    Title          = { fg = c.fg_alt,                  bold = true },
    VisualNOS      = link "Visual",
    WildMenu       = link "Visual",
    Whitespace     = link "NonText",
    StatusLine     = { fg = c.fg_status_line_active,   bg = c.bg_status_line_active },
    StatusLineNC   = { fg = c.fg_status_line_inactive, bg = c.bg_status_line_inactive },
    TabLine        = { fg = c.fg_tab_other,            bg = c.bg_tab_other },
    TabLineSel     = { fg = c.fg_main,                 bg = c.bg_tab_current, bold = true },
    TabLineFill    = { fg = c.fg_dim,                  bg = c.bg_tab_bar },
    WinBar         = link "TabLineSel",
    WinBarNC       = link "TabLine",
    EndOfBuffer    = { fg = c.fg_inactive },
    MatchParen     = { fg = c.fg_main,                 bg = c.bg_paren_match },
    ModeMsg        = { fg = c.fg_dim,                  bold = true },
    MsgArea        = { fg = c.fg_main },
    MoreMsg        = { fg = c.blue },
    VertSplit      = { fg = c.border },
    WinSeparator   = { fg = c.border,                  bold = true },
    DiffAdd        = { fg = c.fg_added,                bg = c.bg_added },
    DiffDelete     = { fg = c.fg_removed,              bg = c.bg_removed },
    DiffChange     = { fg = c.fg_changed,              bg = c.bg_changed },
    DiffText       = { fg = c.fg_changed,              bg = c.bg_changed },
    SpecialKey     = { fg = c.fg_dim },
    SpellBad       = { sp = c.error,                   undercurl = true },
    SpellCap       = { sp = c.warning,                 undercurl = true },
    SpellLocal     = { sp = c.info,                    undercurl = true },
    SpellRare      = { sp = c.hint,                    undercurl = true },
    WarningMsg     = { fg = c.warning },
    Question       = { fg = c.blue },
    Yank           = { fg = "#C8C092",                 bg = "#AA83EC" },
    PortalBlue     = { fg = "#0078ff",                 bg = c.none },
    PortalOrange   = { fg = "#fd6600",                 bg = c.none },

    Comment      = { fg = c.red_faint,   italic = true },
    String       = { fg = c.green_intense },
    Character    = { fg = c.green_intense },
    Boolean      = { fg = c.red_intense, italic = true },
    Statement    = { fg = c.magenta_cooler },
    Conditional  = { fg = c.magenta_faint },
    Repeat       = { fg = c.magenta_cooler },
    Label        = { fg = c.cyan },
    Keyword      = { fg = c.magenta_faint },
    Exception    = { fg = c.magenta_cooler },
    StorageClass = { fg = c.magenta_cooler },
    Structure    = link "Keyword",
    Constant     = { fg = c.fg_main },
    Function     = { fg = c.blue_warmer },
    Identifier   = { fg = c.fg_main },
    Ignore       = link "NonText",
    PreProc      = { fg = c.red_cooler },
    Include      = { fg = c.red_cooler },
    Define       = { fg = c.red_cooler },
    Macro        = { fg = c.red_cooler },
    PreCondit    = { fg = c.red_cooler },
    Todo         = { fg = c.magenta, bold = true },
    Type         = { fg = c.cyan_cooler },
    TypeDef      = { fg = c.cyan_warmer },
    Number       = { fg = c.blue_faint },
    Float        = link "Number",
    Operator     = { fg = c.fg_main },
    Tag          = { fg = c.magenta },
    Property     = { fg = c.fg_main },
    Delimiter    = link "Normal",
    Special      = link "Type",
    SpecialChar  = { fg = c.cyan_faint },
    Underlined   = { fg = c.fg_alt, underline = true },
    Error        = { fg = c.fg_main, bg = c.bg_red_intense },

    qfLineNr   = { fg = c.fg_dim },
    qfFileName = { fg = c.blue },

    htmlH1 = { fg = c.blue,        bold = true },
    htmlH2 = { fg = c.yellow,      bold = true },
    htmlH3 = { fg = c.magenta,     bold = true },
    htmlH4 = { fg = c.green,       bold = true },
    htmlH5 = { fg = c.red,         bold = true },
    htmlH6 = { fg = c.cyan_warmer, bold = true },

    mkdCodeDelimiter = { bg = c.bg_alt,      fg = c.fg_main },
    mkdCodeStart     = { fg = c.cyan_cooler, bold = true },
    mkdCodeEnd       = { fg = c.cyan_cooler, bold = true },

    markdownHeadingDelimiter = { fg = c.rust, bold = true },
    markdownCode             = { fg = c.cyan_cooler },
    markdownCodeBlock        = { fg = c.cyan_cooler },
    markdownLinkText         = { fg = c.blue, underline = true },
    markdownH1               = link "@markup.heading.1",
    markdownH2               = link "@markup.heading.2",
    markdownH3               = link "@markup.heading.3",
    markdownH4               = link "@markup.heading.4",
    markdownH5               = link "@markup.heading.5",
    markdownH6               = link "@markup.heading.6",

    LspCodeLens                 = extends "Float" { italic = false },
    LspCodeLensSeparator        = link "LspCodeLens",
    LspInlayHint                = extends "Float" { bg = c.bg_main },
    LspReferenceText            = { bg = c.bg_blue_intense,  fg = c.fg_main },
    LspReferenceRead            = { bg = c.bg_blue_intense,  fg = c.fg_main },
    LspReferenceWrite           = { bg = c.bg_blue_intense,  fg = c.fg_main },
    LspSignatureActiveParameter = link "Visual",
    LspInfoBorder               = { fg = c.border_highlight, bg = c.bg_main },

    DiagnosticError       = { fg = c.error,   bold = true },
    DiagnosticWarn        = { fg = c.warning, bold = true },
    DiagnosticInfo        = { fg = c.info,    bold = true },
    DiagnosticHint        = { fg = c.hint,    bold = true },
    DiagnosticOk          = { fg = c.ok,      bold = true },
    DiagnosticUnnecessary = { fg = c.fg_dim },

    DiagnosticVirtualTextError = { fg = c.error,   bold = true },
    DiagnosticVirtualTextWarn  = { fg = c.warning, bold = true },
    DiagnosticVirtualTextInfo  = { fg = c.info,    bold = true },
    DiagnosticVirtualTextHint  = { fg = c.hint,    bold = true },
    DiagnosticVirtualTextOk    = { fg = c.ok,      bold = true },

    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn  = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo  = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint  = { undercurl = true, sp = c.hint },
    DiagnosticUnderlineOk    = { undercurl = true, sp = c.ok },

    ["@variable"]                   = link "Identifier",
    ["@variable.builtin"]           = link "Identifier",
    ["@parameter"]                  = link "Identifier",
    ["@variable.parameter"]         = { fg = c.cyan },
    ["@variable.parameter.builtin"] = { fg = c.cyan_faint },
    ["@variable.member"]            = link "Identifier",

    ["@constant"]         = link "Constant",
    ["@constant.builtin"] = link "Special",
    ["@preproc"]          = link "PreProc",
    ["@macro"]            = link "Macro",
    ["@constant.macro"]   = link "Define",
    ["@define"]           = link "Define",

    ["@include"]        = link "Include",
    ["@module"]         = link "Include",
    ["@module.builtin"] = link "Conditional",
    ["@label"]          = link "Label",

    ["@string"]                = link "String",
    ["@string.documentation"]  = { fg = c.green_faint, italic = true },
    ["@string.regex"]          = { fg = c.green_cooler },
    ["@string.regexp"]         = { fg = c.green_cooler },
    ["@string.escape"]         = { fg = c.yellow_faint },
    ["@string.special"]        = { fg = c.red_faint },
    ["@string.special.symbol"] = link "Identifier",
    ["@string.special.path"]   = { fg = c.blue },
    ["@string.special.url"]    = { fg = c.cyan_cooler },

    ["@character"]         = link "Character",
    ["@character.special"] = link "SpecialChar",

    ["@boolean"]      = link "Boolean",
    ["@conditional"]  = link "Conditional",
    ["@number"]       = link "Number",
    ["@float"]        = link "Float",
    ["@number.float"] = link "Float",

    ["@type"]            = link "Type",
    ["@structure"]       = link "Structure",
    ["@type.builtin"]    = link "Type",
    ["@type.definition"] = link "Typedef",

    ["@attribute"]         = link "PreProc",
    ["@attribute.builtin"] = link "PreProc",
    ["@property"]          = link "@field",
    ["@field"]             = link "Property",

    ["@exception"] = link "Exception",
    ["@debug"]     = link "Debug",

    ["@repeat"]       = link "Repeat",
    ["@storageclass"] = link "StorageClass",

    ["@method"]               = link "Function",
    ["@function"]             = link "Function",
    ["@function.call"]        = link "@function",
    ["@function.macro"]       = link "Macro",
    ["@function.method"]      = link "Function",
    ["@function.builtin"]     = link "@function",
    ["@function.method.call"] = link "@function.method",

    ["@constructor"]     = { fg = c.yellow_cooler },
    ["@constructor.lua"] = link "Keyword",
    ["@operator"]        = link "Operator",

    ["@keyword"]           = link "Keyword",
    ["@keyword.coroutine"] = link "@keyword",
    ["@keyword.function"]  = link "@keyword",
    ["@keyword.operator"]  = link "@operator",
    ["@keyword.import"]    = link "Include",
    ["@keyword.type"]      = link "@keyword",
    ["@keyword.label"]     = link "Label",
    ["@keyword.modifier"]  = link "@keyword",
    ["@keyword.repeat"]    = link "Repeat",
    ["@keyword.return"]    = { fg = c.red_intense },
    ["@keyword.debug"]     = link "Debug",
    ["@keyword.exception"] = link "Exception",
    ["@keyword.vim"]       = link "Statement",

    ["@keyword.conditional"]         = link "Conditional",
    ["@keyword.conditional.ternary"] = link "Conditional",

    ["@keyword.directive"]        = link "PreProc",
    ["@keyword.directive.define"] = link "Define",

    ["@punctuation"]           = link "Delimiter",
    ["@punctuation.delimiter"] = link "Delimiter",
    ["@punctuation.bracket"]   = { fg = c.fg_main },
    ["@punctuation.special"]   = { fg = c.fg_main },

    ["@comment"]               = link "Comment",
    ["@comment.documentation"] = link "@string.documentation",

    ["@comment.error"]   = { fg = c.error },
    ["@comment.warning"] = { fg = c.warning },
    ["@comment.todo"]    = link "Todo",
    ["@comment.note"]    = { fg = c.hint },

    ["@markup.strong"]        = { bold = true },
    ["@markup.italic"]        = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"]     = { underline = true },

    ["@markup.heading"]   = link "Title",
    ["@markup.heading.1"] = { fg = c.blue,        bold = true },
    ["@markup.heading.2"] = { fg = c.yellow,      bold = true },
    ["@markup.heading.3"] = { fg = c.magenta,     bold = true },
    ["@markup.heading.4"] = { fg = c.green,       bold = true },
    ["@markup.heading.5"] = { fg = c.red,         bold = true },
    ["@markup.heading.6"] = { fg = c.cyan_warmer, bold = true },

    ["@markup.quote"] = { italic = true },
    ["@markup.math"]  = link "Special",

    ["@markup.link"]              = { fg = c.cyan_cooler },
    ["@markup.link.label"]        = link "SpecialChar",
    ["@markup.link.label.symbol"] = link "Identifier",
    ["@markup.link.url"]          = link "Underlined",

    ["@markup.italic.markdown_inline"]     = link "Exception",
    ["@markup.link.label.markdown_inline"] = link "Property",
    ["@markup.list.markdown"]              = link "Function",
    ["@markup.raw.markdown_inline"]        = link "String",

    ["@markup.raw"]       = link "String",
    ["@markup.raw.block"] = link "String",

    ["@markup.list"]           = { fg = c.fg_main },
    ["@markup.list.checked"]   = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.yellow },

    ["@diff.plus"]  = link "DiffAdd",
    ["@diff.minus"] = link "DiffDelete",
    ["@diff.delta"] = link "DiffChange",

    ["@tag"]           = link "Label",
    ["@tag.attribute"] = link "@property",
    ["@tag.delimiter"] = link "Delimiter",

    ["@text.literal"]   = link "String",
    ["@text.reference"] = link "Identifier",
    ["@text.title"]     = link "Title",
    ["@text.todo"]      = link "Todo",
    ["@text.underline"] = link "Underlined",
    ["@text.uri"]       = link "Underlined",

    ["@none"] = {},

    ["@lsp.type.namespace.python"] = link "@variable",

    ["@lsp.type.boolean"]                      = link "@boolean",
    ["@lsp.type.builtinType"]                  = link "@type.builtin",
    ["@lsp.type.comment"]                      = link "@comment",
    ["@lsp.type.decorator"]                    = link "@attribute",
    ["@lsp.type.deriveHelper"]                 = link "@attribute",
    ["@lsp.type.enum"]                         = link "@type",
    ["@lsp.type.enumMember"]                   = link "@constant",
    ["@lsp.type.escapeSequence"]               = link "@string.escape",
    ["@lsp.type.formatSpecifier"]              = link "@markup.list",
    ["@lsp.type.generic"]                      = link "@variable",
    ["@lsp.type.interface"]                    = { fg = c.blue_warmer },
    ["@lsp.type.keyword"]                      = link "@keyword",
    ["@lsp.type.lifetime"]                     = link "@keyword.storage",
    ["@lsp.type.namespace"]                    = link "@module",
    ["@lsp.type.number"]                       = link "@number",
    ["@lsp.type.operator"]                     = link "@operator",
    ["@lsp.type.parameter"]                    = link "@variable.parameter",
    ["@lsp.type.property"]                     = link "@property",
    ["@lsp.type.selfKeyword"]                  = link "@variable.builtin",
    ["@lsp.type.selfTypeKeyword"]              = link "@variable.builtin",
    ["@lsp.type.string"]                       = link "@string",
    ["@lsp.type.typeAlias"]                    = link "@type.definition",
    ["@lsp.type.unresolvedReference"]          = { undercurl = true, sp = c.error },
    ["@lsp.type.variable"]                     = {},
    ["@lsp.typemod.class.defaultLibrary"]      = link "@type.builtin",
    ["@lsp.typemod.enum.defaultLibrary"]       = link "@type.builtin",
    ["@lsp.typemod.enumMember.defaultLibrary"] = link "@constant.builtin",
    ["@lsp.typemod.function.defaultLibrary"]   = link "@function.builtin",
    ["@lsp.typemod.keyword.async"]             = link "@keyword.coroutine",
    ["@lsp.typemod.keyword.injected"]          = link "@keyword",
    ["@lsp.typemod.macro.defaultLibrary"]      = link "@function.builtin",
    ["@lsp.typemod.method.defaultLibrary"]     = link "@function.builtin",
    ["@lsp.typemod.operator.injected"]         = link "@operator",
    ["@lsp.typemod.string.injected"]           = link "@string",
    ["@lsp.typemod.struct.defaultLibrary"]     = link "@type.builtin",
    ["@lsp.typemod.type.defaultLibrary"]       = { fg = c.blue_cooler },
    ["@lsp.typemod.typeAlias.defaultLibrary"]  = { fg = c.blue_cooler },
    ["@lsp.typemod.variable.callable"]         = link "@function",
    ["@lsp.typemod.variable.defaultLibrary"]   = link "@variable.builtin",
    ["@lsp.typemod.variable.injected"]         = link "@variable",
    ["@lsp.typemod.variable.static"]           = link "@constant",
    ["@lsp.mod.readonly"]                      = link "Constant",
    ["@lsp.type.variable.lua"]                 = link "@lsp.type.variable",
    ["@lsp.typemod.keyword.documentation.lua"] = link "Special",
    ["@lsp.typemod.variable.global"]           = link "Constant",

    DiagnosticFloatingError      = link "DiagnosticError",
    DiagnosticFloatingHint       = link "DiagnosticHint",
    DiagnosticFloatingInfo       = link "DiagnosticInfo",
    DiagnosticFloatingOk         = link "DiagnosticOk",
    DiagnosticFloatingWarn       = link "DiagnosticWarn",
    DiagnosticSignError          = link "DiagnosticError",
    DiagnosticSignHint           = link "DiagnosticHint",
    DiagnosticSignInfo           = link "DiagnosticInfo",
    DiagnosticSignOk             = link "DiagnosticOk",
    DiagnosticSignWarn           = link "DiagnosticWarn",


    -- diff
    DiffAdded     = extends "DiffAdd" { bg = c.none },
    DiffDeleted   = extends "DiffDelete" { bg = c.none },
    DiffChanged   = extends "DiffChange" { bg = c.none },
    DiffOldFile   = { fg = c.yellow },
    DiffNewFile   = { fg = c.yellow_warmer },
    DiffFile      = { fg = c.blue },
    DiffLine      = { fg = c.fg_alt },
    DiffIndexLine = { fg = c.magenta },
    DiffRemoved   = link "DiffDeleted",

    -- mini.diff
    MiniDiffSignAdd    = { fg = c.fg_added_intense,   bg = c.bg_added },
    MiniDiffSignChange = { fg = c.fg_changed_intense, bg = c.bg_changed },
    MiniDiffSignDelete = { fg = c.fg_removed_intense, bg = c.bg_removed },

    -- Neogit
    NeogitBranch               = { fg = c.magenta },
    NeogitRemote               = { fg = c.magenta_cooler },
    NeogitHunkHeader           = { fg = c.fg_main, bg = c.bg_dim },
    NeogitHunkHeaderHighlight  = { fg = c.blue,    bg = c.bg_blue_nuanced },
    NeogitDiffContextHighlight = { fg = c.fg_dim,  bg = c.bg_dim },
    NeogitDiffDeleteHighlight  = link "DiffDelete",
    NeogitCommitViewHeader     = link "DiffText",
    NeogitDiffAdd              = link "DiffAdd",
    NeogitDiffAddHighlight     = link "DiffAdd",
    NeogitDiffDelete           = link "DiffDelete",
    NeogitHunkHeaderCursor     = link "NeogitHunkHeaderHighlight",

    -- NeoVim
    healthError   = { fg = c.error },
    healthSuccess = { fg = c.green_cooler },
    healthWarning = { fg = c.warning },

    -- Scrollbar
    ScrollbarHandle       = { fg = c.none,           bg = c.bg_hl_line },
    ScrollbarSearchHandle = { fg = c.yellow_warmer,  bg = c.bg_hl_line },
    ScrollbarSearch       = { fg = c.yellow_warmer,  bg = c.none },
    ScrollbarErrorHandle  = { fg = c.error,          bg = c.bg_hl_line },
    ScrollbarError        = { fg = c.error,          bg = c.none },
    ScrollbarWarnHandle   = { fg = c.warning,        bg = c.bg_hl_line },
    ScrollbarWarn         = { fg = c.warning,        bg = c.none },
    ScrollbarInfoHandle   = { fg = c.info,           bg = c.bg_hl_line },
    ScrollbarInfo         = { fg = c.info,           bg = c.none },
    ScrollbarHintHandle   = { fg = c.hint,           bg = c.bg_hl_line },
    ScrollbarHint         = { fg = c.hint,           bg = c.none },
    ScrollbarMiscHandle   = { fg = c.magenta_cooler, bg = c.bg_hl_line },
    ScrollbarMisc         = { fg = c.magenta_cooler, bg = c.none },

    -- Mini
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword                = { bg = c.fg_dim },
    MiniCursorwordCurrent         = { bg = c.fg_dim },
    MiniIndentscopeSymbol         = { fg = c.blue_warmer,    nocombine = true },
    MiniIndentscopePrefix         = { nocombine = true },
    MiniJump                      = { bg = c.magenta_cooler, fg = c.fg_main },
    MiniJump2dSpot                = { fg = c.magenta_cooler, bold = true, nocombine = true },
    MiniStarterCurrent            = { nocombine = true },
    MiniStarterFooter             = { fg = c.yellow,         italic = true },
    MiniStarterHeader             = { fg = c.blue },
    MiniStarterInactive           = { fg = c.fg_dim },
    MiniStarterItem               = link "Normal",
    MiniStarterItemBullet         = { fg = c.border },
    MiniStarterItemPrefix         = { fg = c.yellow_cooler },
    MiniStarterSection            = { fg = c.blue_warmer },
    MiniStarterQuery              = { fg = c.blue_cooler },
    MiniSurround                  = { bg = c.yellow_warmer,  fg = c.fg_main },
    MiniTablineCurrent            = link "TabLineSel",
    MiniTablineFill               = link "TabLineFill",
    MiniTablineHidden             = link "TabLine",
    MiniTablineModifiedCurrent    = { fg = c.yellow_cooler,  bg = c.bg_tab_current },
    MiniTablineModifiedHidden     = { bg = c.bg_tab_other,   fg = c.yellow_faint },
    MiniTablineModifiedVisible    = { fg = c.yellow_cooler,  bg = c.bg_alt },
    MiniTablineTabpagesection     = { bg = c.bg_alt,         fg = c.none },
    MiniTablineVisible            = { fg = c.fg_main,        bg = c.bg_alt },
    MiniTestEmphasis              = { bold = true },
    MiniTestFail                  = { fg = c.red,            bold = true },
    MiniTestPass                  = { fg = c.green,          bold = true },
    MiniTrailspace                = { fg = c.red_intense,    bg = c.red_intense },
    MiniClueBorder                = link "FloatBorder",
    MiniClueDescGroup             = link "DiagnosticFloatingWarn",
    MiniClueDescSingle            = link "NormalFloat",
    MiniClueNextKey               = link "DiagnosticFloatingHint",
    MiniClueNextKeyWithPostkeys   = link "DiagnosticFloatingError",
    MiniClueSeparator             = link "DiagnosticFloatingInfo",
    MiniClueTitle                 = link "FloatTitle",
    MiniDiffSignAdd               = link "DiffAdd",
    MiniDiffSignChange            = link "DiffChange",
    MiniDiffSignDelete            = link "DiffDelete",
    MiniIndentscopeSymbol         = link "Special",
    MiniOperatorsExchangeFrom     = link "IncSearch",
    MiniPickNormal                = link "Normal",
    MiniPickPrompt                = link "Normal",
    MiniPickPromptCaret           = link "Cursor",
    MiniPickPromptPrefix          = link "Normal",
    MiniSurround                  = link "IncSearch",

    -- mini.statusline
    MiniStatuslineDevinfo         = { fg = c.blue_faint,             bg = c.bg_status_line_active,   bold = true },
    MiniStatuslineFileinfo        = { fg = c.fg_status_line_active,  bg = c.bg_status_line_active },
    MiniStatuslineFilename        = { fg = c.fg_status_line_active,  bg = c.bg_status_line_active },
    MiniStatuslineInactive        = { fg = c.fg_status_line_inactive,bg = c.bg_status_line_inactive, bold = true },
    MiniStatuslineBrackets        = extends "Operator" { bg = c.bg_hl_line },
    MiniStatuslineDevinfoB        = link "CursorLine",
    MiniStatuslineModeNormal      = { fg = c.bg_main,                bg = c.blue_faint,              bold = true },
    MiniStatuslineModeInsert      = { fg = c.bg_main,                bg = c.green_faint,             bold = true },
    MiniStatuslineModeCommand     = { fg = c.bg_main,                bg = c.yellow_faint,            bold = true },
    MiniStatuslineModeVisual      = { fg = c.bg_main,                bg = c.magenta_faint,           bold = true },
    MiniStatuslineModeVisualBlock = link "MiniStatuslineModeVisual",
    MiniStatuslineModeVisualLine  = link "MiniStatuslineModeVisual",
    MiniStatuslineModeTerminal    = { fg = "#E6C484",                bg = "#181820",                 bold = true },
    MiniStatuslineModeReplace     = { fg = c.bg_dim,                 bg = c.red_faint,               bold = true },
    MiniStatuslineModeDebug       = { fg = "#C8C092",                bg = "#E82626",                 bold = true },
    MiniStatuslineModeSelect      = { fg = "#A0B6CA",                bg = "#7D9CD8",                 bold = true },
    MiniStatuslineModeOther       = { fg = c.bg_dim,                 bg = c.cyan_faint,              bold = true },
    StatuslineNormal              = link "MiniStatuslineModeNormal",
    StatuslineVisual              = link "MiniStatuslineModeVisual",
    StatuslineReplace             = link "MiniStatuslineModeReplace",
    StatuslineCommand             = link "MiniStatuslineModeCommand",
    StatuslineBNormal             = { fg = "#5B7786",                bg = c.bg_hl_line,              bold = true },
    StatuslineBVisual             = { fg = "#5E57A2",                bg = c.bg_hl_line,              bold = true },
    StatuslineBReplace            = { fg = "#CC6D00",                bg = c.bg_hl_line,              bold = true },
    StatuslineBCommand            = { fg = "#BFA36E",                bg = c.bg_hl_line,              bold = true },
    StatusDiffAdded               = extends "DiffAdded" { bg = c.bg_hl_line },
    StatusDiffChanged             = extends "DiffChanged" { bg = c.bg_hl_line },
    StatusDiffDeleted             = extends "DiffDeleted" { bg = c.bg_hl_line },

    CmpDocumentation         = link "Normal",
    CmpDocumentationBorder   = { fg = c.border,      bg = bg_main },
    CmpGhostText             = { fg = c.fg_dim },
    CmpItemAbbr              = { fg = c.fg_main,     bg = c.none },
    CmpItemAbbrDeprecated    = { fg = c.fg_dim,      bg = c.none, strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.blue_warmer, bg = c.none },
    CmpItemAbbrMatchFuzzy    = { fg = c.blue_warmer, bg = c.none },
    CmpItemMenu              = { fg = c.fg_alt,      bg = c.none },
    CmpItemKindDefault       = { fg = c.fg_dim,      bg = c.none },
    CmpItemKindCopilot       = { fg = c.cyan_cooler, bg = c.none },
    CmpItemKindCodeium       = { fg = c.cyan_cooler, bg = c.none },
    CmpItemKindTabNine       = { fg = c.cyan_cooler, bg = c.none },
    CmpItemKindArray         = link "@punctuation.bracket",
    CmpItemKindBoolean       = link "@lsp.type.boolean",
    CmpItemKindClass         = link "@type",
    CmpItemKindColor         = link "Special",
    CmpItemKindConstant      = link "@constant",
    CmpItemKindConstructor   = link "@constructor",
    CmpItemKindEnum          = link "@lsp.type.enum",
    CmpItemKindEnumMember    = link "@lsp.type.enumMember",
    CmpItemKindEvent         = link "Special",
    CmpItemKindField         = link "@variable.member",
    CmpItemKindFile          = link "Normal",
    CmpItemKindFolder        = link "Directory",
    CmpItemKindFunction      = link "@function",
    CmpItemKindInterface     = link "@lsp.type.interface",
    CmpItemKindKey           = link "@variable.member",
    CmpItemKindKeyword       = link "@lsp.type.keyword",
    CmpItemKindMethod        = link "@function.method",
    CmpItemKindModule        = link "@module",
    CmpItemKindNamespace     = link "@module",
    CmpItemKindNull          = link "@constant.builtin",
    CmpItemKindNumber        = link "@number",
    CmpItemKindObject        = link "@constant",
    CmpItemKindOperator      = link "@operator",
    CmpItemKindPackage       = link "@module",
    CmpItemKindProperty      = link "@property",
    CmpItemKindReference     = link "@markup.link",
    CmpItemKindSnippet       = link "Conceal",
    CmpItemKindString        = link "@string",
    CmpItemKindStruct        = link "@lsp.type.struct",
    CmpItemKindUnit          = link "@lsp.type.struct",
    CmpItemKindText          = link "@markup",
    CmpItemKindTypeParameter = link "@lsp.type.typeParameter",
    CmpItemKindVariable      = link "@variable",
    CmpItemKindValue         = link "@string",
    CmpCompletion            = link "Pmenu",
    CmpCompletionSbar        = link "PmenuSbar",
    CmpCompletionThumb       = link "PmenuThumb",
    CmpDocumentationBorder   = link "FloatBorder",
    CmpDocumentation         = link "NormalFloat",
    CmpItemAbbrMatchFuzzy    = link "CmpItemAbbrMatch",
    CmpItemKindDefault       = link "MsgArea",
    CmpItemMenu              = link "MsgArea",
    CmpCompletionBorder      = { fg = "#81B4CA", bg = c.border },
    CmpCompletionSel         = { fg = c.none,    bg = "#E4D795" },
    CmpItemKindEvent         = { fg = "#274F42", bg = "#4FA187", standout = true },

    BlinkCmpDocBorder            = link "CmpDocumentationBorder",
    BlinkCmpDoc                  = link "CmpDocumentation",
    BlinkCmpGhostText            = link "Comment",
    BlinkCmpItemAbbr             = link "CmpItemAbbr",
    BlinkCmpItemAbbrDeprecated   = link "CmpItemAbbrDeprecated",
    BlinkCmpItemAbbrMatch        = link "CmpItemAbbrMatch",
    BlinkCmpItemAbbrMatchFuzzy   = link "CmpItemAbbrMatchFuzzy",
    BlinkCmpItemKindDefault      = link "CmpItemKindDefault",
    BlinkCmpItemMenu             = link "CmpItemMenu",
    BlinkCmpKindClass            = link "CmpItemKindClass",
    BlinkCmpKindClassSel         = link "BlinkCmpKindClass",
    BlinkCmpKindColor            = link "CmpItemKindColor",
    BlinkCmpKindColorSel         = link "BlinkCmpKindColor",
    BlinkCmpKindConstant         = link "CmpItemKindConstant",
    BlinkCmpKindConstantSel      = link "BlinkCmpKindConstant",
    BlinkCmpKindConstructor      = link "CmpItemKindConstructor",
    BlinkCmpKindConstructorSel   = link "BlinkCmpKindConstructor",
    BlinkCmpKindCopilot          = link "CmpItemKindCopilot",
    BlinkCmpKindCopilotSel       = link "BlinkCmpKindCopilot",
    BlinkCmpKindEnum             = link "CmpItemKindEnum",
    BlinkCmpKindEnumMember       = link "CmpItemKindEnumMember",
    BlinkCmpKindEnumMemberSel    = link "BlinkCmpKindEnumMember",
    BlinkCmpKindEnumSel          = link "BlinkCmpKindEnum",
    BlinkCmpKindEvent            = link "CmpItemKindEvent",
    BlinkCmpKindEventSel         = link "BlinkCmpKindEvent",
    BlinkCmpKindField            = link "CmpItemKindField",
    BlinkCmpKindFieldSel         = link "BlinkCmpKindField",
    BlinkCmpKindFile             = link "CmpItemKindFile",
    BlinkCmpKindFileSel          = link "BlinkCmpKindFile",
    BlinkCmpKindFolder           = link "CmpItemKindFolder",
    BlinkCmpKindFolderSel        = link "BlinkCmpKindFolder",
    BlinkCmpKindFunction         = link "CmpItemKindFunction",
    BlinkCmpKindFunctionSel      = link "BlinkCmpKindFunction",
    BlinkCmpKindInterface        = link "CmpItemKindInterface",
    BlinkCmpKindInterfaceSel     = link "BlinkCmpKindInterface",
    BlinkCmpKindKeyword          = link "CmpItemKindKeyword",
    BlinkCmpKindKeywordSel       = link "BlinkCmpKindKeyword",
    BlinkCmpKindMethod           = link "CmpItemKindMethod",
    BlinkCmpKindMethodSel        = link "BlinkCmpKindMethod",
    BlinkCmpKindModule           = link "CmpItemKindModule",
    BlinkCmpKindModuleSel        = link "BlinkCmpKindModule",
    BlinkCmpKindOperator         = link "CmpItemKindOperator",
    BlinkCmpKindOperatorSel      = link "BlinkCmpKindOperator",
    BlinkCmpKindProperty         = link "CmpItemKindProperty",
    BlinkCmpKindPropertySel      = link "BlinkCmpKindProperty",
    BlinkCmpKindReference        = link "CmpItemKindReference",
    BlinkCmpKindReferenceSel     = link "BlinkCmpKindReference",
    BlinkCmpKindSnippet          = link "CmpItemKindSnippet",
    BlinkCmpKindSnippetSel       = link "BlinkCmpKindSnippet",
    BlinkCmpKindStruct           = link "CmpItemKindStruct",
    BlinkCmpKindStructSel        = link "BlinkCmpKindStruct",
    BlinkCmpKindText             = link "CmpItemKindText",
    BlinkCmpKindTextSel          = link "BlinkCmpKindText",
    BlinkCmpKindTypeParameter    = link "CmpItemKindTypeParameter",
    BlinkCmpKindTypeParameterSel = link "BlinkCmpKindTypeParameter",
    BlinkCmpKindUnit             = link "CmpItemKindUnit",
    BlinkCmpKindUnitSel          = link "BlinkCmpKindUnit",
    BlinkCmpKindValue            = link "CmpItemKindValue",
    BlinkCmpKindValueSel         = link "BlinkCmpKindValue",
    BlinkCmpKindVariable         = link "CmpItemKindVariable",
    BlinkCmpKindVariableSel      = link "BlinkCmpKindVariable",
    BlinkCmpMenuBorder           = link "CmpCompletionBorder",
    BlinkCmpMenu                 = link "CmpCompletion",
    BlinkCmpMenuSelection        = link "CmpCompletionSel",
    BlinkCmpScrollBarGutter      = link "CmpCompletionSbar",
    BlinkCmpScrollBarThumb       = link "CmpCompletionThumb",

    -- multicursor
    MultiCursorCursor            = link "Cursor",
    MultiCursorDisabledCursor    = link "Visual",
    MultiCursorDisabledVisual    = link "Visual",
    MultiCursorVisual            = link "Visual",

    -- dap ui
    DapUIBreakpointsDisabledLine = link "Comment",
    DapUIBreakpointsInfo         = link "DiagnosticInfo",
    DapUIBreakpointsPath         = link "Directory",
    DapUIFloatBorder             = link "Special",
    DapUILineNumber              = link "Special",
    DapUIPlayPause               = link "String",
    DapUIRestart                 = link "String",
    DapUIScope                   = link "Special",
    DapUISource                  = link "Special",
    DapUIStepBack                = link "Special",
    DapUIStepInto                = link "Special",
    DapUIStepOut                 = link "Special",
    DapUIStepOver                = link "Special",
    DapUIStop                    = link "DiagnosticError",
    DapUIStoppedThread           = link "Special",
    DapUIThread                  = link "Identifier",
    DapUIType                    = link "Type",
    DapUIUnavailable             = link "Comment",
    DapUIWatchesEmpty            = link "DiagnosticError",
    DapUIWatchesError            = link "DiagnosticError",
    DapUIWatchesValue            = link "Identifier",
    Debug                        = link "Special",

    -- hydra
    HydraBorder                  = link "FloatBorder",
    HydraFooter                  = link "FloatFooter",
    HydraHint                    = link "NormalFloat",
    HydraTitle                   = link "FloatTitle",
}

local tries = 0
local max_tries = vim.tbl_count(definitions)

local queue = vim.ringbuf(max_tries)
for k in pairs(definitions) do
    queue:push(k)
end

while queue:peek() and tries <= max_tries do
    local k = queue:pop()
    local v = definitions[k]

    if type(v) == "table" then
        vim.api.nvim_set_hl(0, k, v)

    elseif type(v) == "function" then
        local res = v()
        if res then
            vim.api.nvim_set_hl(0, k, res)
        else
            queue:push(k)
            tries = tries + 1
        end
    end
end

if queue:peek() then
    print("keys not set:")
    vim.print(vim.iter(queue)
        :fold({}, function (acc, k, v)
            table.insert(acc, k)
            return acc
        end))
end
